import { db } from "../db";
import { conceptosMedioPago, clientes, empresas, type CategoriaConcepto, type NivelConcepto, type TipoSatCatalogo } from "@shared/schema";
import { eq } from "drizzle-orm";

interface ConceptoLegal {
  nombre: string;
  tipo: "percepcion" | "deduccion";
  categoria: CategoriaConcepto;
  nivel: NivelConcepto;
  satClave: string | null;
  satTipoCatalogo: TipoSatCatalogo | null;
  formula: string;
  limiteExento: string | null;
  gravableISR: boolean;
  integraSBC: boolean;
  limiteAnual: string | null;
  fundamentoLegal: string;
  ordenCalculo: number;
}

const CONCEPTOS_LEGALES: ConceptoLegal[] = [
  // ============================================================================
  // NIVEL SAT - PERCEPCIONES (Solo lectura excepto super admin)
  // ============================================================================
  {
    nombre: "Sueldos y Salarios",
    tipo: "percepcion",
    categoria: "salario",
    nivel: "sat",
    satClave: "001",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DIAS_TRABAJADOS",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 82-89",
    ordenCalculo: 10,
  },
  {
    nombre: "Aguinaldo",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "002",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DIAS_AGUINALDO",
    limiteExento: "30 * UMA_DIARIA",
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 87, LISR Art. 93 Fracc. XIV",
    ordenCalculo: 20,
  },
  {
    nombre: "PTU (Reparto de Utilidades)",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "003",
    satTipoCatalogo: "percepcion",
    formula: "PTU_CALCULADO",
    limiteExento: "15 * UMA_DIARIA",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 117-131, LISR Art. 93 Fracc. XIV",
    ordenCalculo: 30,
  },
  // ============================================================================
  // NIVEL PREVISIÓN SOCIAL - Beneficios y Previsión Social (configurables)
  // ============================================================================
  {
    nombre: "Reembolso de Gastos Médicos",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "004",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_REEMBOLSO",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. VI",
    ordenCalculo: 100,
  },
  {
    nombre: "Fondo de Ahorro",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "005",
    satTipoCatalogo: "percepcion",
    formula: "APORTACION_EMPRESA",
    limiteExento: "13% SALARIO si aportación igual patrón/trabajador",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: "1.3 * UMA_ANUAL",
    fundamentoLegal: "LISR Art. 93 Fracc. XI",
    ordenCalculo: 100,
  },
  {
    nombre: "Caja de Ahorro",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "006",
    satTipoCatalogo: "percepcion",
    formula: "APORTACION_CAJA",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. XI",
    ordenCalculo: 100,
  },
  {
    nombre: "Bono de Puntualidad",
    tipo: "percepcion",
    categoria: "bonos_incentivos",
    nivel: "sat",
    satClave: "010",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_BONO",
    limiteExento: "10% SALARIO_PERIODO",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. I",
    ordenCalculo: 50,
  },
  {
    nombre: "Prima de Seguro de Vida",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "011",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_PRIMA",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. XXI",
    ordenCalculo: 100,
  },
  {
    nombre: "Seguro de Gastos Médicos Mayores",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "012",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_PRIMA",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. VI",
    ordenCalculo: 100,
  },
  {
    nombre: "Subsidios por Incapacidad",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "014",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_SUBSIDIO",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LSS Art. 96-99",
    ordenCalculo: 100,
  },
  {
    nombre: "Becas para Trabajadores e Hijos",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "015",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_BECA",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. VIII",
    ordenCalculo: 100,
  },
  {
    nombre: "Horas Extra",
    tipo: "percepcion",
    categoria: "horas_extra",
    nivel: "sat",
    satClave: "019",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_HORA * HORAS_EXTRA * FACTOR_PAGO",
    limiteExento: "MIN(SALARIO_HORA * MIN(HORAS_EXTRA_DOBLES, 9) * 2, SALARIO_PERIODO * 0.5)",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 67-68, LISR Art. 93 Fracc. I",
    ordenCalculo: 40,
  },
  {
    nombre: "Prima Dominical",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "020",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DOMINGOS_TRABAJADOS * 0.25",
    limiteExento: "1 * UMA_SEMANAL",
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 71, LISR Art. 93 Fracc. I",
    ordenCalculo: 45,
  },
  {
    nombre: "Prima Vacacional",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "021",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DIAS_VACACIONES * 0.25",
    limiteExento: "15 * UMA_DIARIA",
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 80, LISR Art. 93 Fracc. XIV",
    ordenCalculo: 25,
  },
  {
    nombre: "Prima de Antigüedad",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "022",
    satTipoCatalogo: "percepcion",
    formula: "12 * SALARIO_DIARIO * AÑOS_SERVICIO",
    limiteExento: "90 * UMA_DIARIA * AÑOS_SERVICIO",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 162, LISR Art. 93 Fracc. XIII",
    ordenCalculo: 200,
  },
  {
    nombre: "Vacaciones",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "023",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DIAS_VACACIONES",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 76-81",
    ordenCalculo: 24,
  },
  {
    nombre: "Comisiones",
    tipo: "percepcion",
    categoria: "bonos_incentivos",
    nivel: "sat",
    satClave: "028",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_COMISION",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 285-291",
    ordenCalculo: 60,
  },
  {
    nombre: "Vales de Despensa",
    tipo: "percepcion",
    categoria: "vales",
    nivel: "prevision_social",
    satClave: "029",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_VALES",
    limiteExento: "0.40 * UMA_MENSUAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. VIII",
    ordenCalculo: 100,
  },
  {
    nombre: "Días Festivos Laborados",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "035",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * DIAS_FESTIVOS_TRABAJADOS * 2",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 74-75",
    ordenCalculo: 46,
  },
  {
    nombre: "Indemnización 3 Meses",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "025",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * 90",
    limiteExento: "90 * UMA_DIARIA por cada año",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 48, 50, LISR Art. 93 Fracc. XIII",
    ordenCalculo: 200,
  },
  {
    nombre: "Indemnización 20 Días por Año",
    tipo: "percepcion",
    categoria: "prestaciones_ley",
    nivel: "sat",
    satClave: "027",
    satTipoCatalogo: "percepcion",
    formula: "SALARIO_DIARIO * 20 * AÑOS_SERVICIO",
    limiteExento: "90 * UMA_DIARIA * AÑOS_SERVICIO",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 50, LISR Art. 93 Fracc. XIII",
    ordenCalculo: 200,
  },
  {
    nombre: "Bono de Asistencia",
    tipo: "percepcion",
    categoria: "bonos_incentivos",
    nivel: "sat",
    satClave: "049",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_BONO",
    limiteExento: "10% SALARIO_PERIODO",
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. I",
    ordenCalculo: 51,
  },
  // ============================================================================
  // NIVEL SAT - DEDUCCIONES
  // ============================================================================
  {
    nombre: "Seguridad Social (IMSS Trabajador)",
    tipo: "deduccion",
    categoria: "impuestos",
    nivel: "sat",
    satClave: "001",
    satTipoCatalogo: "deduccion",
    formula: "IMSS_ENF_MAT + IMSS_INV_VIDA + IMSS_CES_VEJEZ",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LSS Art. 25",
    ordenCalculo: 300,
  },
  {
    nombre: "ISR (Impuesto Sobre la Renta)",
    tipo: "deduccion",
    categoria: "impuestos",
    nivel: "sat",
    satClave: "002",
    satTipoCatalogo: "deduccion",
    formula: "TABLA_ISR_2025(BASE_GRAVABLE) - SUBSIDIO_EMPLEO",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 96, 97, 98",
    ordenCalculo: 310,
  },
  {
    nombre: "Infonavit (Crédito Vivienda)",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "sat",
    satClave: "004",
    satTipoCatalogo: "deduccion",
    formula: "DESCUENTO_INFONAVIT",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "Ley Infonavit Art. 29 Fracc. III",
    ordenCalculo: 320,
  },
  {
    nombre: "Pensión Alimenticia",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "sat",
    satClave: "007",
    satTipoCatalogo: "deduccion",
    formula: "MONTO_PENSION o SALARIO_NETO * PORCENTAJE",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 110 Fracc. V",
    ordenCalculo: 330,
  },
  {
    nombre: "Fonacot (Crédito)",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "sat",
    satClave: "011",
    satTipoCatalogo: "deduccion",
    formula: "DESCUENTO_FONACOT",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "Ley Fonacot Art. 3",
    ordenCalculo: 340,
  },
  {
    nombre: "Cuota Sindical",
    tipo: "deduccion",
    categoria: "sindicato",
    nivel: "sat",
    satClave: "012",
    satTipoCatalogo: "deduccion",
    formula: "SALARIO_PERIODO * PORCENTAJE_SINDICAL",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 110 Fracc. VI",
    ordenCalculo: 350,
  },
  {
    nombre: "Subsidio al Empleo",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "002",
    satTipoCatalogo: "otro_pago",
    formula: "SUBSIDIO_TABLA_2025(BASE_GRAVABLE)",
    limiteExento: "MONTO_TOTAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 98",
    ordenCalculo: 400,
  },
  {
    nombre: "Ayuda para Gastos Funerarios",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "017",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_AYUDA",
    limiteExento: "1 * SMG_ANUAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. IV",
    ordenCalculo: 100,
  },
  {
    nombre: "Vales de Restaurante",
    tipo: "percepcion",
    categoria: "vales",
    nivel: "prevision_social",
    satClave: "029",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_VALES",
    limiteExento: "0.40 * UMA_MENSUAL",
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 93 Fracc. VIII",
    ordenCalculo: 100,
  },
  {
    nombre: "Vales de Gasolina",
    tipo: "percepcion",
    categoria: "vales",
    nivel: "prevision_social",
    satClave: "029",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_VALES",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 94",
    ordenCalculo: 100,
  },
  {
    nombre: "Ayuda para Transporte",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "042",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_AYUDA",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 94",
    ordenCalculo: 100,
  },
  {
    nombre: "Ayuda para Renta",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "043",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_AYUDA",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 94",
    ordenCalculo: 100,
  },
  {
    nombre: "Ayuda para Artículos Escolares",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "044",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_AYUDA",
    limiteExento: null,
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 94",
    ordenCalculo: 100,
  },
  {
    nombre: "Ayuda para Anteojos",
    tipo: "percepcion",
    categoria: "prevision_social",
    nivel: "prevision_social",
    satClave: "046",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_AYUDA",
    limiteExento: null,
    gravableISR: true,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LISR Art. 94",
    ordenCalculo: 100,
  },
  // ============================================================================
  // NIVEL ADICIONAL - Completamente configurables por empresa
  // ============================================================================
  {
    nombre: "Gratificación Especial",
    tipo: "percepcion",
    categoria: "bonos_incentivos",
    nivel: "adicional",
    satClave: "038",
    satTipoCatalogo: "percepcion",
    formula: "MONTO_GRATIFICACION",
    limiteExento: null,
    gravableISR: true,
    integraSBC: true,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 84",
    ordenCalculo: 100,
  },
  {
    nombre: "Anticipo de Sueldo",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "adicional",
    satClave: "004",
    satTipoCatalogo: "deduccion",
    formula: "MONTO_ANTICIPO",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 110 Fracc. I",
    ordenCalculo: 400,
  },
  {
    nombre: "Préstamo Empresa",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "adicional",
    satClave: "004",
    satTipoCatalogo: "deduccion",
    formula: "ABONO_PRESTAMO",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 110 Fracc. I",
    ordenCalculo: 400,
  },
  {
    nombre: "Días no Laborados",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "adicional",
    satClave: "006",
    satTipoCatalogo: "deduccion",
    formula: "SALARIO_DIARIO * DIAS_AUSENTES",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 47, 110",
    ordenCalculo: 400,
  },
  {
    nombre: "Horas no Laboradas",
    tipo: "deduccion",
    categoria: "descuentos",
    nivel: "adicional",
    satClave: "006",
    satTipoCatalogo: "deduccion",
    formula: "SALARIO_HORA * HORAS_AUSENTES",
    limiteExento: null,
    gravableISR: false,
    integraSBC: false,
    limiteAnual: null,
    fundamentoLegal: "LFT Art. 110",
    ordenCalculo: 400,
  },
];

export async function seedConceptosLegales(): Promise<void> {
  console.log("🌱 Seeding catálogo de conceptos unificado...");

  const [cliente] = await db.select().from(clientes).limit(1);
  const [empresa] = await db.select().from(empresas).limit(1);

  if (!cliente || !empresa) {
    console.log("⚠️ No hay cliente o empresa en el sistema. Saltando seed de conceptos.");
    return;
  }

  let insertados = 0;
  let actualizados = 0;
  let errores = 0;

  for (const concepto of CONCEPTOS_LEGALES) {
    try {
      const existing = await db
        .select()
        .from(conceptosMedioPago)
        .where(eq(conceptosMedioPago.nombre, concepto.nombre))
        .limit(1);

      if (existing.length > 0) {
        await db
          .update(conceptosMedioPago)
          .set({
            nivel: concepto.nivel,
            satClave: concepto.satClave,
            satTipoCatalogo: concepto.satTipoCatalogo,
            fundamentoLegal: concepto.fundamentoLegal,
            ordenCalculo: concepto.ordenCalculo,
            categoria: concepto.categoria,
            formula: concepto.formula,
            limiteExento: concepto.limiteExento,
            limiteAnual: concepto.limiteAnual,
            gravableISR: concepto.gravableISR,
            integraSBC: concepto.integraSBC,
          })
          .where(eq(conceptosMedioPago.id, existing[0].id));
        actualizados++;
      } else {
        await db.insert(conceptosMedioPago).values({
          clienteId: cliente.id,
          empresaId: empresa.id,
          nombre: concepto.nombre,
          tipo: concepto.tipo,
          categoria: concepto.categoria,
          nivel: concepto.nivel,
          satClave: concepto.satClave,
          satTipoCatalogo: concepto.satTipoCatalogo,
          fundamentoLegal: concepto.fundamentoLegal,
          ordenCalculo: concepto.ordenCalculo,
          formula: concepto.formula,
          limiteExento: concepto.limiteExento,
          limiteAnual: concepto.limiteAnual,
          gravableISR: concepto.gravableISR,
          integraSBC: concepto.integraSBC,
          activo: true,
        });
        insertados++;
      }
    } catch (error: any) {
      if (!error.message?.includes("duplicate key")) {
        console.error(`Error procesando concepto ${concepto.nombre}:`, error.message);
        errores++;
      }
    }
  }

  console.log(`✅ Catálogo de conceptos: ${insertados} insertados, ${actualizados} actualizados, ${errores} errores`);
}

export const VARIABLES_FORMULA = [
  { variable: "SALARIO_DIARIO", descripcion: "Salario diario del empleado", ejemplo: "350.00" },
  { variable: "SALARIO_HORA", descripcion: "Salario por hora (SALARIO_DIARIO / 8)", ejemplo: "43.75" },
  { variable: "SALARIO_PERIODO", descripcion: "Salario del periodo completo", ejemplo: "5,250.00" },
  { variable: "DIAS_TRABAJADOS", descripcion: "Días trabajados en el periodo", ejemplo: "15" },
  { variable: "DIAS_PERIODO", descripcion: "Total de días del periodo de nómina", ejemplo: "15" },
  { variable: "DIAS_TRABAJADOS_ANIO", descripcion: "Días trabajados en el año", ejemplo: "180" },
  { variable: "DIAS_VACACIONES", descripcion: "Días de vacaciones según antigüedad (LFT Art. 76)", ejemplo: "12" },
  { variable: "DIAS_AGUINALDO", descripcion: "Días de aguinaldo a pagar (mínimo 15, proporcional)", ejemplo: "15" },
  { variable: "AÑOS_SERVICIO", descripcion: "Años de antigüedad del empleado", ejemplo: "3" },
  { variable: "UMA_DIARIA", descripcion: "Unidad de Medida y Actualización diaria 2025", ejemplo: "113.14" },
  { variable: "UMA_MENSUAL", descripcion: "UMA mensual (UMA_DIARIA * 30.4)", ejemplo: "3,439.46" },
  { variable: "UMA_ANUAL", descripcion: "UMA anual (UMA_DIARIA * 365)", ejemplo: "41,296.10" },
  { variable: "SALARIO_MINIMO", descripcion: "Salario mínimo diario general 2025", ejemplo: "278.80" },
  { variable: "SALARIO_MINIMO_FRONTERA", descripcion: "Salario mínimo diario zona frontera 2025", ejemplo: "419.88" },
  { variable: "SBC_DIARIO", descripcion: "Salario Base de Cotización diario", ejemplo: "380.50" },
  { variable: "SBC_PERIODO", descripcion: "SBC del periodo (SBC_DIARIO * DIAS_PERIODO)", ejemplo: "5,707.50" },
  { variable: "SDI", descripcion: "Salario Diario Integrado", ejemplo: "385.00" },
  { variable: "BASE_GRAVABLE", descripcion: "Base gravable para ISR del periodo", ejemplo: "4,800.00" },
  { variable: "HORAS_EXTRA", descripcion: "Total de horas extra trabajadas", ejemplo: "9" },
  { variable: "HORAS_EXTRA_DOBLES", descripcion: "Horas extra dobles trabajadas", ejemplo: "6" },
  { variable: "HORAS_EXTRA_TRIPLES", descripcion: "Horas extra triples trabajadas", ejemplo: "3" },
  { variable: "FACTOR_PAGO", descripcion: "Factor de pago para horas extra (2 o 3)", ejemplo: "2" },
  { variable: "DOMINGOS_TRABAJADOS", descripcion: "Cantidad de domingos trabajados en el periodo", ejemplo: "2" },
  { variable: "DIAS_FESTIVOS_TRABAJADOS", descripcion: "Días festivos oficiales trabajados", ejemplo: "1" },
  { variable: "MONTO_BONO", descripcion: "Monto del bono asignado", ejemplo: "500.00" },
  { variable: "MONTO_VALES", descripcion: "Monto de vales de despensa", ejemplo: "1,200.00" },
  { variable: "MONTO_AYUDA", descripcion: "Monto de ayuda/apoyo económico", ejemplo: "800.00" },
  { variable: "PORCENTAJE_SINDICAL", descripcion: "Porcentaje de cuota sindical acordado", ejemplo: "0.02" },
  { variable: "DESCUENTO_INFONAVIT", descripcion: "Descuento quincenal por crédito Infonavit", ejemplo: "850.00" },
  { variable: "DESCUENTO_FONACOT", descripcion: "Descuento por crédito Fonacot", ejemplo: "500.00" },
];
